---
title: "Intro to R: Cheat sheet"
format: 
  html:
    css: styles.css
    self-contained: true
    page-layout: full
    grid:
      sidebar-width: 10px
      body-width: 900px
      margin-width: 400px
editor: visual
toc: true
---

# Introduction to R

# Module 1

## Packages

-   **Packages**: collections of R functions, data, and compiled code in a well-defined format, created to add specific functionality.

(Attributions if I need them: Tool and toolbox by FreePik, shed by Paul J)

## select()

-   *Purpose:*To select the columns we want from the data
-   *Why:*Because it is easier to deal with fewer columns and it uses less space on your computer
-   *Example:*You want to create a linelist for analysis and remove columns that are not needed
-   *How:*We type out the names of the columns we want

## select examples

-   select(**data**)
-   select(data, **col1**): Select col1
-   select(data, **-col1**): Deselect or remove col1
-   select(data, col1, **col2**): Select col1 and col2
-   select(data, col1, col2, **col3**)
-   select(data, col1, col2, ..., **col100**)

# Module 1: Part 2

pronounce tabyl\@

# Module 3: Part 1

## Demo - might remove?

1)  Open up RStudio

2)  Show them the different panes

3)  Open up a new R script

4)  Remind them of some key principles:

    -   Write sum(1,1) in the script
    -   Run it, and highlight how you can see it in the console (parallel to exercise??)
    -   Assign sum(1,1) to an object and highlight how it appears in the environment
    -   Assign another object and highlight how the environment can store many different objects
    -   Assign yet another but this time a character, and highlight how R colours in functions, strings, and numbers differently

5)  Tidy your script and higlight importance of tidy script

    -   Explain comments, and add title and name etc at the top
    -   Add sections using ctrl + shift + R
