---
title: "Surveillance report"
format: 
  docx:
    reference-doc: "template.docx" 
---

```{r setup}
#| echo: false
pacman::p_load(dplyr, 
               ggplot2, 
               flextable, 
               here)

# linelist <- readRDS(here("data/Disease_x_2025-05-21.rds"))
linelist <- readRDS(here("data/Viraland_cholera_2021-05-25_linelist_clean.rds"))
```

# Epidemiology of disease X

## Summary

There have been `r nrow(linelist)` cases of *disease X* across `r nrow(linelist |> distinct(region))` regions.

```{r table_region}
#| echo: false

linelist |> 
  group_by(region) |> 
  summarise(count = n()) |> 
  flextable() |> 
  autofit()
```

## Cases over time

The most recent case was reported on `r max(linelist$date_report)`.

**Epicurve of cases over time, by report date**

```{r plot_reportdate}
#| echo: false

ggplot(data = linelist) +
  geom_histogram(aes(x = date_report), binwidth = 1, color = "white") +
  theme_minimal()
```

::: landscape
:::

::: callout-tip
Some content here
:::

::: {layout-ncol="2"}
This is the content for the first column.

**Epicurve of cases over time, by report date**

```{r plot_reportdate2}
#| echo: false

ggplot(data = linelist) +
  geom_histogram(aes(x = date_report), binwidth = 1, color = "white") +
  theme_minimal()
```
:::
